spring:
# 只是一些基本属性
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ikedb?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Root1234
    #type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
